
export const CREATE_TUTORIAL     = "CREATE_TUTORIAL";
export const RETRIEVE_TUTORIALS  = "RETRIEVE_TUTORIALs";
export const UPADATE_TUTORIAL    = "UPDATE_TUTORIAL";
export const DELETE_TUTORIAL     = "DELETE_TUTORIAL";
export const DELETE_ALL_TUTORIAL = "DELETE_ALL_TUTORIAL";